#!/bin/bash

paths=();
export_line=();
cache=~/.cache_alios;
groupid="group"

paths=( /var/mobile/Containers/Data/Application/*/Library/Preferences\
        /var/mobile/Containers/Shared/AppGroup/*/Library/Preferences    )

function check_plist {
    let z=0;     
    for i in ${paths[*]}
    do 
        for j in $(find $i | grep -i plist)
        do
            appName=${j##*/}
            if [[ $appName == *"$groupid"* ]];then
                app=${j##*/group.}; app=${app%*.plist};
                subpath="/var/mobile/Containers/Shared/AppGroup/";
            else
                app=${j##*/}; app=${app%*.plist}; 
                subpath="/var/mobile/Containers/Data/Application/";
            fi
                path=$j; 
                name=${app##*.}; 
                uuid=${path%%/Library*}; uuid=${uuid##*/};
                #echo -e "\e[1m$app: \e[1m$uuid\e[0m \e[39m$name\e\_\e[30m\e[7m\e[33m $z\e[0m";
                echo -ne "\e[39m$name\e\_\e[30m\e[7m\e[33m $z\e[0m\n";
                echo  'path'$z=$subpath$uuid >> $cache; echo 'open'$z=$name >> $cache;
                let "z++";
            done
        done
    }

function map_plist {
   source -- "$cache"
   #echo  'alias 'app$2'='\'cd "${ap["$3"'path']}"\'
   #echo  "${2^^}=${ap["$3"'path']}"
   #echo  "${2}=${ap["$3"'open']}"
}


if [ "$1" = "plist" ]; then
    paths=("$2") && check_plist && exit;
elif [ "$1" = "-m" ]; then
   source ~/.alioscache;
    map_plist $2 $3 
else
    check_plist;
    printf "%`tput cols`s"|tr ' ' '_'
fi

