#!/bin/bash

#ios7+ 
#Like alias + keeps track of changing UUIDs directory names and updates path for alias when there is any change in path.
#First set up your mark ( use iFile, Filza.. ) by creating empty file 'somename.als' in Documents folder of apps you want to access by alias (/var/mobile/Containers/Data/Application/<UUID>/Documents) and run 'alios && bash'
#Now you can jump through UUIDs just by typing 'somename'
#Will work even after backup/restore as marks are backed up in iCloud  

   ##################### usage #############
   ## 0.  create your name.als  
   ## 1.  alios   		
   ## 2.  logout/login	     
   ## 3.  name - will get you behind uuid
   #########################################				        

#Now marked UUIDsare being tracked, in case you want to add more marks make sure you run "alios -f" afterwards, it will make fresh check

fileOut=$HOME/Documents/.alios
dataPath=/var/mobile/Containers/Shared/AppGroup
#docDir=Storage
vnames=''

function rcapend { 
		echo '/usr/bin/alios && . ~/Documents/.alios' >> $HOME/.bashrc #'save state into into rc for next run
	    	return
}

function alios {
    echo -n 'setting..'
    if  [ -f "$fileOut" ]; then rm -f "$fileOut" && touch "$fileOut"
    else
        touch $fileOut
    fi

	for j in $(ls -A $dataPath)
	do
       	appDataUUID=$j
       	appDataUUIDPATH="$dataPath/$appDataUUID"
		appNameMe=$(ls -A $appDataUUIDPATH | grep -F '.als')
			if [ "$appNameMe" ]; then	
				suffix=".als"	
				appName=${appNameMe%$suffix}
				export appName=${appNameMe%$suffix}
	   			echo "$appName=$appDataUUIDPATH" >> $fileOut
				echo "alias $appName='cd $appDataUUIDPATH'" >> $fileOut
				echo -n '.'
				#echo -n "$appName "
			fi
	done
	uuidCheck 
	rccheck
}

function uuidCheck {
    for i in $(cat "$fileOut" | grep -v 'alias')
    do
	    dpath=${i#*=}
	    vname=${i%%=*}
	    vnames="$vnames $vname"
	    if [ ! -d "$dpath" ]; then
        	alios
	    fi
    done
#	echo $(cat $fileOut)
	appName=${appNameMe%$suffix}
    printf "\n>>$vnames"
    rccheck
}

function rccheck {    
	isinrc=$(cat $HOME/.bashrc |grep -F '.alios')
	if [ "$isinrc" == '/usr/bin/alios && . ~/Documents/.alios' ]; then
		return
	else rcapend
	fi
}

if [ "$1" == "" ]; then 
	if [ ! -f "$fileOut" ]; then
		alios
		else uuidCheck
	fi
else alios
fi
printf "\nready\n"
