#!/bin/bash

perl=$(perl -v);
perl_string="This is perl";

if [[ $perl == *"$perl_string"* ]];then
    ln -s /usr/bin/alios.pl /usr/bin/alios
    /usr/bin/alios -i
    /usr/bin/alios -s
else
    ln -s /usr/bin/alios.sh /usr/bin/alios
fi

chown mobile:mobile /var/mobile/.alios*





